sonar.projectKey=RoronoaFilip_Calorie_Tracker
sonar.projectName=Calorie_Tracker
sonar.organization=roronoafilip

sonar.python.version=3.14

sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml