"""Proves the desktop app imports what the dailyplate-phone web app produces.

The files in tests/fixtures/phone are generated by the phone app (``npm run fixtures:export`` in that
repository). If its output format changes, regenerate them there and copy them here.
"""

import tempfile
import unittest
import zipfile
from datetime import date
from pathlib import Path

from calorie_tracker.infrastructure.database import Database
from calorie_tracker.infrastructure.diary_csv_importer import CsvDiaryImporter
from calorie_tracker.infrastructure.importer import CsvFoodImporter
from calorie_tracker.infrastructure.intake import (
    KIND_DIARY, KIND_FOODS, KIND_IMAGE, build_intake_plan,
)
from calorie_tracker.infrastructure.repositories import FoodRepository

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "phone"


class PhoneExportTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.work = Path(self.temp.name) / "work"
        database = Database(Path(self.temp.name) / "data" / "tracker.sqlite3")
        database.initialize()
        self.foods = FoodRepository(database)

    def test_the_zip_is_a_valid_zip_that_follows_the_folder_rules(self):
        with zipfile.ZipFile(FIXTURES / "phone-export.zip") as archive:
            self.assertIsNone(archive.testzip())
            names = archive.namelist()
        self.assertEqual(sorted(names), [
            "diary-2026-10-05.csv", "diary-2026-10-06.csv", "foods.csv", "photos/barcode-001.jpg",
        ])

    def test_the_intake_plan_orders_everything_and_reads_the_diary_dates(self):
        plan = build_intake_plan([FIXTURES / "phone-export.zip"], self.work)
        self.assertEqual(plan.problems, ())
        self.assertEqual([item.kind for item in plan.items], [KIND_FOODS, KIND_IMAGE, KIND_DIARY, KIND_DIARY])
        self.assertEqual([item.diary_date for item in plan.items if item.kind == KIND_DIARY],
                         [date(2026, 10, 5), date(2026, 10, 6)])

    def test_the_foods_file_imports_without_problems(self):
        importer = CsvFoodImporter(self.foods)
        preview = importer.preview(FIXTURES / "foods.csv")
        self.assertEqual(len(preview.foods), 2)
        self.assertEqual(importer.issues_for(importer.read(FIXTURES / "foods.csv")), ())
        result = importer.apply(preview)
        self.assertEqual(result.imported, 2)
        egg = self.foods.search("Phone Egg")[0]
        self.assertEqual(egg.basis, "count")
        self.assertEqual(egg.name, "Phone Egg, large")  # the comma survived quoting

    def test_the_diary_files_match_the_imported_foods_and_guess_the_loose_name(self):
        importer = CsvFoodImporter(self.foods)
        importer.apply(importer.preview(FIXTURES / "foods.csv"))
        diary = CsvDiaryImporter(self.foods)
        first = diary.preview(FIXTURES / "diary-2026-10-05.csv")
        self.assertEqual([row.food_name for row in first.rows], ["Phone Oats", "phone egg large"])
        exact, loose = first.rows
        self.assertIsNotNone(exact.catalogue_item_id)
        self.assertIsNone(loose.catalogue_item_id)  # not an exact match...
        self.assertTrue(loose.suggestions and loose.suggestions[0].confident)  # ...but a confident, flagged guess
        self.assertEqual(loose.suggestions[0].name, "Phone Egg, large")
        second = diary.preview(FIXTURES / "diary-2026-10-06.csv")
        self.assertIsNotNone(second.rows[0].catalogue_item_id)


if __name__ == "__main__":
    unittest.main()
